apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: guestbookappset
  labels: 
    harness.io/envRef: "engineering{{ cluster.clusterName }}gitops"
    harness.io/serviceRef: "gitopsapplicationsetsvc"
spec:  
  generators:  
    - git:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        revision: HEAD  
        files:  
        - path: "applicationset/git-generator-files-discovery/cluster-config/**/config.json"  
  template:  
    metadata:  
      name: '{{cluster.name}}-guestbook-appsetgenerated'  
    spec:  
      project: "0e964829"
      source:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        targetRevision: HEAD  
        path: "applicationset/git-generator-files-discovery/apps/guestbook"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: '{{cluster.namespace}}'
      syncPolicy:  
        automated: {}
