apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: guestbookappset
spec:  
  generators:  
    - git:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        revision: HEAD  
        files:  
        - path: "applicationset/test-json/cluster-config/**/config.json"  
  template:  
    metadata:  
      name: '{{cluster.name}}-guestbook-appsetgenerated'
      labels: 
        harness.io/envRef: 'engineering{{cluster.clusterName}}gitops'
        harness.io/serviceRef: "testjson"      
    spec:  
      project: "0e964829"
      source:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        targetRevision: HEAD  
        path: "applicationset/test-json/apps/guestbook"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: '{{cluster.namespace}}'
      syncPolicy:  
        automated: {}
