apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: testjsonappset
spec:  
  generators:  
    - git:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        revision: HEAD  
        files:  
        - path: "applicationset/test-json/engineering**/config.json"  
  template:
    metadata:
      name: 'testjson-app'
      labels: 
        harness.io/envRef: 'engineering{{cluster.clusterName}}gitops'
        harness.io/serviceRef: "testjson"      
    spec:
      replicas: '{{spec.replicas}}'
      project: "0e964829"
      source:  
        repoURL: https://github.com/lorenyeung/gitops-examples.git  
        targetRevision: HEAD  
        path: "applicationset/test-json/apps/guestbook"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - PrunePropagationPolicy=undefined
          - CreateNamespace=true
          - Validate=true
          - PruneLast=false
          - ApplyOutOfSyncOnly=false
          - FluxSubsystem=false
          - AutoCreateFluxResources=false
          - Replace=false
          - retry=false
